#node block

FROM node:alpine3.16 as frontend
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# #nginx block

FROM nginx:1.23-alpine
COPY --from=frontend /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]

